export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch tokens
        "primary":                    "#ffb0cf",
        "secondary":                  "#cabeff",
        "tertiary":                   "#ffb951",
        "background":                 "#10102e",
        "surface":                    "#10102e",
        "surface-dim":                "#10102e",
        "surface-container-lowest":   "#0a0a28",
        "surface-container-low":      "#181836",
        "surface-container":          "#1c1c3b",
        "surface-container-high":     "#272746",
        "surface-container-highest":  "#323251",
        "surface-bright":             "#363656",
        "surface-variant":            "#323251",
        "surface-tint":               "#ffb0cf",
        "on-surface":                 "#e2dfff",
        "on-surface-variant":         "#dac0c8",
        "on-background":              "#e2dfff",
        "on-primary":                 "#63003c",
        "on-primary-container":       "#780d4a",
        "on-primary-fixed":           "#3d0023",
        "on-primary-fixed-variant":   "#841954",
        "on-secondary":               "#31009a",
        "on-secondary-fixed":         "#1c0062",
        "on-secondary-container":     "#bcaeff",
        "on-secondary-fixed-variant": "#4717ca",
        "on-tertiary":                "#452b00",
        "on-tertiary-container":      "#573700",
        "on-tertiary-fixed":          "#291800",
        "on-tertiary-fixed-variant":  "#633f00",
        "primary-container":          "#ff7eb9",
        "primary-fixed":              "#ffd9e5",
        "primary-fixed-dim":          "#ffb0cf",
        "secondary-container":        "#4a1ccc",
        "secondary-fixed":            "#e6deff",
        "secondary-fixed-dim":        "#cabeff",
        "tertiary-container":         "#df9c33",
        "tertiary-fixed":             "#ffddb3",
        "tertiary-fixed-dim":         "#ffb951",
        "error":                      "#ffb4ab",
        "error-container":            "#93000a",
        "on-error":                   "#690005",
        "on-error-container":         "#ffdad6",
        "outline":                    "#a28b92",
        "outline-variant":            "#554248",
        "inverse-surface":            "#e2dfff",
        "inverse-on-surface":         "#2d2d4d",
        "inverse-primary":            "#a3346c",
        // Legacy dn-* aliases
        "dn-bg":          "#10102e",
        "dn-surface":     "#1c1c3b",
        "dn-surface-lo":  "#181836",
        "dn-surface-hi":  "#272746",
        "dn-surface-top": "#323251",
        "dn-rose":        "#ffb0cf",
        "dn-rose-bright": "#ff7eb9",
        "dn-violet":      "#cabeff",
        "dn-amber":       "#ffb951",
        "dn-text":        "#e2dfff",
        "dn-muted":       "#dac0c8",
        "dn-outline":     "#a28b92",
      },
      borderRadius: {
        DEFAULT:  "1rem",
        lg:       "2rem",
        xl:       "3rem",
        full:     "9999px",
        pill:     "9999px",
        card:     "1.5rem",
        "card-lg": "2rem",
      },
      spacing: {
        xs:            "4px",
        base:          "8px",
        sm:            "12px",
        gutter:        "16px",
        "safe-margin": "20px",
        md:            "24px",
        lg:            "40px",
        xl:            "64px",
      },
      fontFamily: {
        "display-lg":         ['"Playfair Display"', "serif"],
        "display-lg-mobile":  ['"Playfair Display"', "serif"],
        "headline-md":        ['"Playfair Display"', "serif"],
        "headline-md-mobile": ['"Playfair Display"', "serif"],
        "title-sm":           ['"Plus Jakarta Sans"', "sans-serif"],
        "body-md":            ['"Plus Jakarta Sans"', "sans-serif"],
        "label-caps":         ['"Plus Jakarta Sans"', "sans-serif"],
        display: ['"Playfair Display"', "serif"],
        sans:    ['"Plus Jakarta Sans"', "sans-serif"],
      },
      fontSize: {
        "display-lg":        ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md":       ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md-mobile":["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "title-sm":          ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md":           ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps":        ["12px", { lineHeight: "1",   letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
